-- MySQL Script generated by MySQL Workbench
-- Fri Apr 21 00:25:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CV_Project_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CV_Project_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CV_Project_db` DEFAULT CHARACTER SET utf8 ;
USE `CV_Project_db` ;

-- -----------------------------------------------------
-- Table `CV_Project_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`User` (
  `idUser` INT NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME NULL,
  `is_superuser` TINYINT NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NULL,
  `email` VARCHAR(254) NULL,
  `is_staff` TINYINT NOT NULL,
  `is_active` TINYINT NOT NULL,
  `date_joined` DATETIME NOT NULL,
  `first_name` VARCHAR(150) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Profile` (
  `idProfile` INT NOT NULL AUTO_INCREMENT,
  `birthday_date` DATETIME NULL,
  `gender` VARCHAR(6) NULL,
  `phone_number` VARCHAR(15) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idProfile`, `User_idUser`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  INDEX `fk_Profile_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `CV_Project_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Main Education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Main Education` (
  `idMain Education` INT NOT NULL,
  `level` VARCHAR(45) NULL,
  `degree` VARCHAR(45) NULL,
  PRIMARY KEY (`idMain Education`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Resume` (
  `idResume` INT NOT NULL,
  `Profile_idProfile` INT NOT NULL,
  `Profile_User_idUser` INT NOT NULL,
  `about_me` MEDIUMTEXT NULL,
  `soft_skills` MEDIUMTEXT NULL,
  `Main Education_idMain Education` INT NOT NULL,
  `position` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idResume`, `Profile_idProfile`, `Profile_User_idUser`, `Main Education_idMain Education`),
  INDEX `fk_Resume_Profile1_idx` (`Profile_idProfile` ASC, `Profile_User_idUser` ASC) VISIBLE,
  INDEX `fk_Resume_Main Education1_idx` (`Main Education_idMain Education` ASC) VISIBLE,
  CONSTRAINT `fk_Resume_Profile1`
    FOREIGN KEY (`Profile_idProfile` , `Profile_User_idUser`)
    REFERENCES `CV_Project_db`.`Profile` (`idProfile` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resume_Main Education1`
    FOREIGN KEY (`Main Education_idMain Education`)
    REFERENCES `CV_Project_db`.`Main Education` (`idMain Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Links` (
  `idLinks` INT NOT NULL,
  `Profile_idProfile` INT NOT NULL,
  `Profile_User_idUser` INT NOT NULL,
  `Twitter` VARCHAR(150) NULL,
  `Facebook` VARCHAR(150) NULL,
  `LinkedIn` VARCHAR(150) NULL,
  `VK` VARCHAR(150) NULL,
  `Instagram` VARCHAR(150) NULL,
  `HeadHunter` VARCHAR(150) NULL,
  PRIMARY KEY (`idLinks`, `Profile_idProfile`, `Profile_User_idUser`),
  INDEX `fk_Links_Profile1_idx` (`Profile_idProfile` ASC, `Profile_User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Links_Profile1`
    FOREIGN KEY (`Profile_idProfile` , `Profile_User_idUser`)
    REFERENCES `CV_Project_db`.`Profile` (`idProfile` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Institution` (
  `idInstitution` INT NOT NULL,
  `UUID` INT NOT NULL,
  `title` VARCHAR(150) NULL,
  `description` MEDIUMTEXT NULL,
  `Main Education_idMain Education` INT NOT NULL,
  `website_url` VARCHAR(150) NULL,
  `diploma` BLOB NULL,
  `completed_date` DATE NULL,
  PRIMARY KEY (`idInstitution`, `Main Education_idMain Education`),
  INDEX `fk_Institution_Main Education1_idx` (`Main Education_idMain Education` ASC) VISIBLE,
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE,
  CONSTRAINT `fk_Institution_Main Education1`
    FOREIGN KEY (`Main Education_idMain Education`)
    REFERENCES `CV_Project_db`.`Main Education` (`idMain Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Additional Education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Additional Education` (
  `idAdditional Education` INT NOT NULL,
  `UUID` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `website_url` VARCHAR(150) NULL,
  `diploma` BLOB NULL,
  `Resume_idResume` INT NOT NULL,
  `Resume_Profile_idProfile` INT NOT NULL,
  `Resume_Profile_User_idUser` INT NOT NULL,
  `Resume_Main Education_idMain Education` INT NOT NULL,
  `complition_date` DATE NULL,
  PRIMARY KEY (`idAdditional Education`, `Resume_idResume`, `Resume_Profile_idProfile`, `Resume_Profile_User_idUser`, `Resume_Main Education_idMain Education`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE,
  INDEX `fk_Additional Education_Resume1_idx` (`Resume_idResume` ASC, `Resume_Profile_idProfile` ASC, `Resume_Profile_User_idUser` ASC, `Resume_Main Education_idMain Education` ASC) VISIBLE,
  CONSTRAINT `fk_Additional Education_Resume1`
    FOREIGN KEY (`Resume_idResume` , `Resume_Profile_idProfile` , `Resume_Profile_User_idUser` , `Resume_Main Education_idMain Education`)
    REFERENCES `CV_Project_db`.`Resume` (`idResume` , `Profile_idProfile` , `Profile_User_idUser` , `Main Education_idMain Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Electronic Certificates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Electronic Certificates` (
  `idElectronic Certificates` INT NOT NULL,
  `UUID` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `certificate_url` VARCHAR(150) NULL,
  `certificate` BLOB NULL,
  `completion percentage` INT NULL,
  `Resume_idResume` INT NOT NULL,
  `Resume_Profile_idProfile` INT NOT NULL,
  `Resume_Profile_User_idUser` INT NOT NULL,
  `Resume_Main Education_idMain Education` INT NOT NULL,
  PRIMARY KEY (`idElectronic Certificates`, `Resume_idResume`, `Resume_Profile_idProfile`, `Resume_Profile_User_idUser`, `Resume_Main Education_idMain Education`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE,
  INDEX `fk_Electronic Certificates_Resume1_idx` (`Resume_idResume` ASC, `Resume_Profile_idProfile` ASC, `Resume_Profile_User_idUser` ASC, `Resume_Main Education_idMain Education` ASC) VISIBLE,
  CONSTRAINT `fk_Electronic Certificates_Resume1`
    FOREIGN KEY (`Resume_idResume` , `Resume_Profile_idProfile` , `Resume_Profile_User_idUser` , `Resume_Main Education_idMain Education`)
    REFERENCES `CV_Project_db`.`Resume` (`idResume` , `Profile_idProfile` , `Profile_User_idUser` , `Main Education_idMain Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Skill` (
  `idSkill` INT NOT NULL,
  `UUID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Resume_idResume` INT NOT NULL,
  `Resume_Profile_idProfile` INT NOT NULL,
  `Resume_Profile_User_idUser` INT NOT NULL,
  `Resume_Main Education_idMain Education` INT NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`idSkill`, `Resume_idResume`, `Resume_Profile_idProfile`, `Resume_Profile_User_idUser`, `Resume_Main Education_idMain Education`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Skill_Resume1_idx` (`Resume_idResume` ASC, `Resume_Profile_idProfile` ASC, `Resume_Profile_User_idUser` ASC, `Resume_Main Education_idMain Education` ASC) VISIBLE,
  CONSTRAINT `fk_Skill_Resume1`
    FOREIGN KEY (`Resume_idResume` , `Resume_Profile_idProfile` , `Resume_Profile_User_idUser` , `Resume_Main Education_idMain Education`)
    REFERENCES `CV_Project_db`.`Resume` (`idResume` , `Profile_idProfile` , `Profile_User_idUser` , `Main Education_idMain Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Work_Exp_Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Work_Exp_Section` (
  `idWork_Exp_Section` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `years_interval` VARCHAR(11) NULL,
  `Resume_idResume` INT NOT NULL,
  `Resume_Profile_idProfile` INT NOT NULL,
  `Resume_Profile_User_idUser` INT NOT NULL,
  `Resume_Main Education_idMain Education` INT NOT NULL,
  PRIMARY KEY (`idWork_Exp_Section`, `Resume_idResume`, `Resume_Profile_idProfile`, `Resume_Profile_User_idUser`, `Resume_Main Education_idMain Education`),
  INDEX `fk_Work_Exp_Section_Resume1_idx` (`Resume_idResume` ASC, `Resume_Profile_idProfile` ASC, `Resume_Profile_User_idUser` ASC, `Resume_Main Education_idMain Education` ASC) VISIBLE,
  CONSTRAINT `fk_Work_Exp_Section_Resume1`
    FOREIGN KEY (`Resume_idResume` , `Resume_Profile_idProfile` , `Resume_Profile_User_idUser` , `Resume_Main Education_idMain Education`)
    REFERENCES `CV_Project_db`.`Resume` (`idResume` , `Profile_idProfile` , `Profile_User_idUser` , `Main Education_idMain Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Job` (
  `idProject` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `project_url` VARCHAR(150) NULL,
  `git_url` VARCHAR(150) NULL,
  `start_date` DATETIME NULL,
  `finish_date` DATETIME NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `Work_Exp_Section_idWork_Exp_Section` INT NOT NULL,
  `Work_Exp_Section_Resume_idResume` INT NOT NULL,
  `Work_Exp_Section_Resume_Profile_idProfile` INT NOT NULL,
  `Work_Exp_Section_Resume_Profile_User_idUser` INT NOT NULL,
  `Work_Exp_Section_Resume_Main Education_idMain Education` INT NOT NULL,
  `position` VARCHAR(150) NULL,
  `company` VARCHAR(150) NULL,
  `years_interval` VARCHAR(11) NULL,
  `UUID` INT NOT NULL,
  PRIMARY KEY (`idProject`, `Work_Exp_Section_idWork_Exp_Section`, `Work_Exp_Section_Resume_idResume`, `Work_Exp_Section_Resume_Profile_idProfile`, `Work_Exp_Section_Resume_Profile_User_idUser`, `Work_Exp_Section_Resume_Main Education_idMain Education`),
  INDEX `fk_Project_Work_Exp_Section1_idx` (`Work_Exp_Section_idWork_Exp_Section` ASC, `Work_Exp_Section_Resume_idResume` ASC, `Work_Exp_Section_Resume_Profile_idProfile` ASC, `Work_Exp_Section_Resume_Profile_User_idUser` ASC, `Work_Exp_Section_Resume_Main Education_idMain Education` ASC) VISIBLE,
  CONSTRAINT `fk_Project_Work_Exp_Section1`
    FOREIGN KEY (`Work_Exp_Section_idWork_Exp_Section` , `Work_Exp_Section_Resume_idResume` , `Work_Exp_Section_Resume_Profile_idProfile` , `Work_Exp_Section_Resume_Profile_User_idUser` , `Work_Exp_Section_Resume_Main Education_idMain Education`)
    REFERENCES `CV_Project_db`.`Work_Exp_Section` (`idWork_Exp_Section` , `Resume_idResume` , `Resume_Profile_idProfile` , `Resume_Profile_User_idUser` , `Resume_Main Education_idMain Education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Like` (
  `idLike` INT NOT NULL,
  `session_key` VARCHAR(40) NOT NULL,
  `User_idUser` INT NOT NULL,
  `UUID_key` INT NULL,
  PRIMARY KEY (`idLike`),
  INDEX `fk_Like_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Like_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `CV_Project_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CV_Project_db`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CV_Project_db`.`Comment` (
  `idComment` INT NOT NULL,
  `message` MEDIUMTEXT NULL,
  `Comment_idComment` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `approved` TINYINT NOT NULL,
  `is_deleted` TINYINT NOT NULL,
  `UUID_key` INT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idComment`, `User_idUser`),
  INDEX `fk_Comment_Comment1_idx` (`Comment_idComment` ASC) VISIBLE,
  INDEX `fk_Comment_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Comment1`
    FOREIGN KEY (`Comment_idComment`)
    REFERENCES `CV_Project_db`.`Comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `CV_Project_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
